[tool.poetry]
name = "my-app"
version = "0.1.0"
description = "My cool python app"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.scripts]
my-app-cli = "my_app.main:run" # Optional: defines the entry point
